theme: jekyll-theme-midnight
title: 1000 Blank White Cards Online
description: The online card game you can play however you want!

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jemoji

exclude:
  - .idea/
